### PR TITLE
Preprocessor: Handle potential integer underflow in macro expansion

### LINKED ISSUE #247: Crash: integer overflow due to nested unterminated function-like macro invocation
```c
#define str(s) # s
#define xstr(s) str(s)
#define INCFILE(n) str(strcmp(
xstr(INCFILE(2)) INCFILE(2))
```

```
thread 22572550 panic: integer overflow
/Users/ehaas/source/arocc/src/Preprocessor.zig:1286:69: 0x1053ec56a in Preprocessor.expandMacroExhaustive (arocc)
                    moving_end_idx = moving_end_idx + res.items.len - count;
                                                                    ^
/Users/ehaas/source/arocc/src/Preprocessor.zig:1332:33: 0x105386834 in Preprocessor.expandMacro (arocc)
    try pp.expandMacroExhaustive(tokenizer, &pp.top_expansion_buf, 0, 1, true);
                                ^
/Users/ehaas/source/arocc/src/Preprocessor.zig:393:35: 0x105351354 in Preprocessor.preprocessExtra (arocc)
                try pp.expandMacro(&tokenizer, tok);
                                  ^
/Users/ehaas/source/arocc/src/Preprocessor.zig:184:30: 0x10534c232 in Preprocessor.preprocess (arocc)
    return pp.preprocessExtra(source) catch |err| switch (err) {
```

### PR DESCRIPTION
**Pull request by ehaas**
Nested unterminated macro expansions could underflow `moving_end_idx`

Also addresses a memory leak encountered when eof occurs during
macro argument collection.

Fixes #247

### CODE REVIEW

**Comment by ehaas** [comment]
Two quick observations from fixing this:

1. The saturating arithmetic syntax is easy to remember and, when it makes sense to use it, it's nicer than an explicit `if` or `@xWithOverflow` 
2. The GPA in debug mode made it pretty straightforward to find the leak

File: src/Preprocessor.zig [hunk 1]
```diff
@@ -1281,9 +1282,8 @@ fn expandMacroExhaustive(
                     const count = macro_scan_idx - idx + 1;
                     for (buf.items[idx .. idx + count]) |tok| Token.free(tok.expansion_locs, pp.comp.gpa);
                     try buf.replaceRange(idx, count, res.items);
-                    // TODO: moving_end_idx += res.items.len - (macro_scan_idx-idx+1)
-                    // doesn't work when the RHS is negative (unsigned!)
-                    moving_end_idx = moving_end_idx + res.items.len - count;
+
+                    moving_end_idx = (moving_end_idx + res.items.len) -| count;
```
Comment (Vexu) [inline src/Preprocessor.zig:1286]: This looks good but I want to document it so that I can understand it in the future as well.

My understanding is that `count` should be called `tokens_removed` and `res.items.len` should be called `tokens_added`.  So the easiest to understand version would be
```suggestion
                    moving_end_idx += tokens_added;
                    // Overflow here means that we encountered an unterminated argument list
                    // while expanding the body of this macro.
                    moving_end_idx -|= tokens_removed;
```

**Review by Vexu — APPROVED** [review]
