### PR TITLE
Compilation: use mtime for timestamp macro

### LINKED ISSUE #711: `__TIMESTAMP__` macro has incorrect value
We render the current time for `__TIMESTAMP__` but it is supposed to be "the date and time of the last modification of the current source file"

https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html

Related: #239

### PR DESCRIPTION
**Pull request by danielsan901998**
resolve #711
Added a new argument to generateBuiltinMacros to pass an optional timestamp that is used in the case of not having a valid epoch passed as environment variable, to generate the timestamp from a path  a new function called generateBuiltinMacrosFromPath is created and is used in Driver for each source file instead of having the same builtin.
Changed generateDateAndTime to make the timestamp argument optional, since the stat can fail, and following GCC behavior it will expand timestamp to "??? ??? ?? ??:??:?? ????"

### CODE REVIEW

File: src/aro/Compilation.zig [hunk 1]
```diff
@@ -190,51 +190,45 @@ pub fn getSourceEpoch(self: *const Compilation, max: i64) !?i64 {
...
-        day_name,
-        month_name,
-        month_day.day_index + 1,
-        day_seconds.getHoursIntoDay(),
-        day_seconds.getMinutesIntoHour(),
-        day_seconds.getSecondsIntoMinute(),
-        year_day.year,
-    });
+fn generateDateAndTime(w: anytype, timestamp: ?u47) !void {
+    if (timestamp) |t| {
```
Comment (Vexu) [inline src/aro/Compilation.zig:194]: Could you use `orelse` instead so that the entire function doesn't need to be indented?
```suggestion
fn generateDateAndTime(w: anytype, opt_timestamp: ?u47) !void {
    const timestamp = opt_timestamp orelse { ... };
```

File: src/aro/Compilation.zig [hunk 2]
```diff
@@ -550,8 +544,18 @@ fn generateSystemDefines(comp: *Compilation, w: anytype) !void {
     }
 }
 
+/// Generate builtin macros trying to use mtime as timestamp
+pub fn generateBuiltinMacrosFromPath(comp: *Compilation, system_defines_mode: SystemDefinesMode, path: []const u8) !Source {
+    var buf = std.ArrayList(u8).init(comp.gpa);
+    defer buf.deinit();
+
```
Comment (Vexu) [inline src/aro/Compilation.zig:551]:
```suggestion
```
These look accidental.

File: src/aro/Compilation.zig [hunk 3]
```diff
@@ -587,9 +591,18 @@ pub fn generateBuiltinMacros(comp: *Compilation, system_defines_mode: SystemDefi
...
-    try generateDateAndTime(buf.writer(), timestamp);
+    const provided: ?i64 = comp.getSourceEpoch(max_timestamp) catch blk: {
+        try comp.addDiagnostic(.{
+            .tag = .invalid_source_epoch,
+            .loc = .{ .id = .unused, .byte_offset = 0, .line = 0 },
+        }, &.{});
+        break :blk null;
+    };
+    if (provided) |epoch| {
+        try generateDateAndTime(buf.writer(), @intCast(std.math.clamp(epoch, 0, max_timestamp)));
```
Comment (Vexu) [inline src/aro/Compilation.zig:602]: This clamp could now be moved to `getSourceEpoch` since that's where it's validated.

**Review by Vexu — APPROVED** [review]
Looks good, just needs a few small adjustments.

**Comment by danielsan901998** [comment]
Changes applied

**Comment by Vexu** [comment]
Thanks!
