### PR TITLE
Parser: require integral types for fixed-type enums

### LINKED ISSUE #685: Fixed-underlying-type enums should enforce non-enum integral underlying type
The following are all invalid:
```c
typedef struct {
   int x;
} S;
typedef enum : int {
   A
} E;

enum Bad1: S{
    B1,
};
enum Bad2: E{
    B2,
};

enum Bad3: unsigned * {
    B3,
};
```

### PR DESCRIPTION
**Pull request by ehaas**
Closes #685

### CODE REVIEW

File: src/aro/Parser.zig [hunk 1]
```diff
@@ -2488,7 +2489,12 @@ fn enumSpec(p: *Parser) Error!Type {
             try p.errTok(.enum_fixed, colon);
             break :fixed null;
         };
-        try p.errTok(.enum_fixed, colon);
+        if (fixed.isInt() and !fixed.is(.@"enum")) {
+            try p.errTok(.enum_fixed, colon);
+        } else {
+            try p.errStr(.invalid_type_underlying_enum, ty_start, try p.typeStr(fixed));
+            break :fixed Type.int;
+        }
```
Comment (Vexu) [inline src/aro/Parser.zig:2497]: I think this keeps it clear that the `.enum_fixed` warning is meant to be issued always.
```suggestion

        if (!fixed.isInt() or fixed.is(.@"enum")) {
            try p.errStr(.invalid_type_underlying_enum, ty_start, try p.typeStr(fixed));
            break :fixed Type.int;
        }

        try p.errTok(.enum_fixed, colon);
```

**Review by Vexu — APPROVED** [review]
