### PR TITLE
Preprocessor: Ensure MacroArguments are always fully de-init'ed

### LINKED ISSUE #78: Preprocessor memory leak - unterminated function-like macro invocation
This only manifests on Linux, I wasn't able to reproduce it on MacOS. Zig version `0.9.0-dev.1561+5ebdc8c46` 

```C
#define foo(X) X
foo(1,
```
```
root@006bbb66b04e:/arocc# ./zig-out/bin/arocc -E test/cases/leak.c
test/cases/leak.c:2:1: error: unterminated function macro argument list
foo(1,
^
1 error generated.
foo ( 1 ,
error(gpa): memory address 0x7fd5a77e0380 leaked:
/zig-linux-x86_64-0.9.0-dev.1561+5ebdc8c46/lib/std/array_list.zig:340:69: 0x349579 in std.array_list.ArrayListAligned([]const Tree.Token,null).ensureTotalCapacityPrecise (arocc)
                const new_memory = try self.allocator.reallocAtLeast(self.allocatedSlice(), new_capacity);
                                                                    ^
/zig-linux-x86_64-0.9.0-dev.1561+5ebdc8c46/lib/std/array_list.zig:325:55: 0x27babe in std.array_list.ArrayListAligned([]const Tree.Token,null).ensureTotalCapacity (arocc)
                return self.ensureTotalCapacityPrecise(better_capacity);
                                                      ^
/zig-linux-x86_64-0.9.0-dev.1561+5ebdc8c46/lib/std/array_list.zig:364:41: 0x376b78 in std.array_list.ArrayListAligned([]const Tree.Token,null).addOne (arocc)
            try self.ensureTotalCapacity(newlen);
                                        ^
/zig-linux-x86_64-0.9.0-dev.1561+5ebdc8c46/lib/std/array_list.zig:175:49: 0x3491c6 in std.array_list.ArrayListAligned([]const Tree.Token,null).append (arocc)
            const new_item_ptr = try self.addOne();
                                                ^


error(gpa): memory address 0x7fd5a77e2500 leaked:
/zig-linux-x86_64-0.9.0-dev.1561+5ebdc8c46/lib/std/array_list.zig:340:69: 0x321489 in std.array_list.ArrayListAligned(Tree.Token,null).ensureTotalCapacityPrecise (arocc)
                const new_memory = try self.allocator.reallocAtLeast(self.allocatedSlice(), new_capacity);
                                                                    ^
/zig-linux-x86_64-0.9.0-dev.1561+5ebdc8c46/lib/std/array_list.zig:325:55: 0x27bbde in std.array_list.ArrayListAligned(Tree.Token,null).ensureTotalCapacity (arocc)
                return self.ensureTotalCapacityPrecise(better_capacity);
                                                      ^
/zig-linux-x86_64-0.9.0-dev.1561+5ebdc8c46/lib/std/array_list.zig:364:41: 0x321328 in std.array_list.ArrayListAligned(Tree.Token,null).addOne (arocc)
            try self.ensureTotalCapacity(newlen);
                                        ^
/zig-linux-x86_64-0.9.0-dev.1561+5ebdc8c46/lib/std/array_list.zig:175:49: 0x2fa4c6 in std.array_list.ArrayListAligned(Tree.Token,null).append (arocc)
            const new_item_ptr = try self.addOne();
                                                ^
```

### PR DESCRIPTION
**Pull request by ehaas**
Fixes #78

### CODE REVIEW

File: src/Preprocessor.zig [hunk 1]
```diff
@@ -966,9 +973,6 @@ fn expandMacroExhaustive(pp: *Preprocessor, tokenizer: *Tokenizer, buf: *ExpandB
 
                     var res = try pp.expandFuncMacro(macro_tok.loc, macro, &args, &expanded_args);
                     defer res.deinit();
-                    for (expanded_args.items) |arg| {
```
Comment (ehaas) [inline src/Preprocessor.zig:969]: I'm unsure about this change - was this separate from the `expanded_args.deinit()` for a reason?

Comment (doppioandante) [reply src/Preprocessor.zig:969]: I have written that code but I have no idea why I did this, your change looks good to me.
