### PR TITLE
Preprocessor: handle macros which expand to `defined`

### LINKED ISSUE #337: Macro expansion which produces defined(X)
This is undefined behavior according to the C standard but both gcc and clang treat it like `defined` is a function-like macro:

```c
#define FOO_IS_DEFINED defined(FOO)
#define FOO

#if FOO_IS_DEFINED
#error "FOO is defined"
#endif
```

clang warns `test.c:4:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]`

Both will evaluate the `#if` condition to true and will display the "FOO is defined" error message.

aro currently says `error: function-like macro 'defined' is not defined`

### PR DESCRIPTION
**Pull request by ehaas**
Since `defined` needs to look at its argument before expansion
happens, it needs to be special cased in expandMacroExhaustive.

It can't be a special function-like macro because that will cause
incorrect expansion outside of preprocessor expression contexts.
It can't be handled solely in `Preprocessor.expr` because the
argument will have been expanded by that point.

Closes #337

### CODE REVIEW

File: src/Preprocessor.zig [hunk 1]
```diff
@@ -689,6 +683,59 @@ fn expr(pp: *Preprocessor, tokenizer: *Tokenizer) MacroError!bool {
...
+/// Returns the number of tokens consumed
+fn handleKeywordDefined(pp: *Preprocessor, macro_tok: *Token, tokens: []const Token, eof: RawToken) !usize {
+    std.debug.assert(macro_tok.id == .keyword_defined);
+    var it = TokenIterator.init(tokens);
+    const first = it.nextNoWS() orelse {
+        try pp.err(eof, .macro_name_missing);
+        return it.i;
+    };
+    switch (first.id) {
+        .identifier, .extended_identifier => {
```
Comment (Vexu) [inline src/Preprocessor.zig:696]: This has a bug similar to `__has_feature` that I fixed recently 7c179f6b9402b41e03bf60211bdecd183441d8f8:
```c
#define __const__ a

#if !defined __const__
#error isMacroIdentifier not used
#endif
```

File: src/Preprocessor.zig [hunk 2]
```diff
@@ -1443,13 +1490,44 @@ fn removeExpandedTokens(pp: *Preprocessor, buf: *ExpandBuf, start: usize, len: u
...
+/// expression context (#if or #elif) or not.
+/// In a non-expression context it's just an identifier. Within a preprocessor
+/// expression it is a unary operator or one-argument function.
+const EvalContext = enum {
+    expr,
+    non_expr,
+};
+
+/// Helper for safely iterating over a slice of tokens while skipping whitespace
+const TokenIterator = struct {
```
Comment (Vexu) [inline src/Preprocessor.zig:1503]: This is nice, there are probably other places that could be improved to use this in the future.

**Review by Vexu — APPROVED** [review]
One small bug but otherwise this looks good!
